# Generated by Django 3.0.4 on 2020-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='occupation',
            field=models.CharField(choices=[('Resident', 'Resident'), ('Teacher', 'Teacher')], max_length=10, null=True),
        ),
    ]
