# Generated by Django 3.0.4 on 2020-04-10 20:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_medico_crm'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='avatar',
            field=models.ImageField(null=True, upload_to=accounts.models.Medico.get_upload_handler),
        ),
    ]
