# Generated by Django 3.0.4 on 2020-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_medico_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='occupation',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Resident', 'Resident'), ('Teacher', 'Teacher')], max_length=10, null=True),
        ),
    ]
