# Generated by Django 3.0.4 on 2020-04-12 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('recommendations', models.CharField(max_length=300)),
                ('exam_type', models.CharField(choices=[('Ecocardiograma', 'Ecorcardiograma'), ('Electrocardiograma', 'Electrocardiograma'), ('Mapa', 'Mapa'), ('Holter', 'Holter')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1)),
                ('birth_date', models.DateField(null=True)),
                ('ethinicity', models.CharField(choices=[('Negro', 'Negro'), ('Branco', 'Branco'), ('Pardo', 'Pardo'), ('Indio', 'Indio'), ('Amarelo', 'Amarelo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('realization_date', models.DateField()),
                ('diagnostic', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to=exams.models.Report.get_upload_handler)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Patient'),
        ),
    ]
