# Generated by Django 3.0.4 on 2020-05-26 14:52

from django.db import migrations, models
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200427_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('Provisório', 'Provisório'), ('Reprovado', 'Reprovado'), ('Aprovado', 'Aprovado'), ('Aprovado com Modificação', 'Aprovado com Modificação')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=exams.models.Report.get_upload_handler),
        ),
    ]
