# Generated by Django 3.0.4 on 2020-04-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200404_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
