# Generated by Django 3.0.4 on 2020-05-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20200526_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('Provisório', 'Provisório'), ('Reprovado', 'Reprovado'), ('Aprovado', 'Aprovado'), ('Aprovado com Modificação', 'Aprovado com Modificação')], default=('Provisório', 'Provisório'), max_length=30, null=True),
        ),
    ]
