# Generated by Django 3.0.4 on 2020-06-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20200526_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='approved',
            new_name='emmited',
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('Provisório', 'Provisório'), ('Reprovado', 'Reprovado'), ('Aprovado', 'Aprovado'), ('Aprovado com Modificação', 'Aprovado com Modificação')], default='Provisório', max_length=30, null=True),
        ),
    ]
