# Generated by Django 3.0.4 on 2020-06-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20200602_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='realization_date',
            field=models.DateField(null=True),
        ),
    ]
